### ISSUE TITLE
second to last plan

### ISSUE THREAD

**Issue by Jaehun-Kim22** [Jaehun-Kim22/SCIC_Project#27]
# TODO

- 기영
  - 데이터 랜덤하게 나누는 10가지 버전 만들기
  - 
- 주희
  - augmentation 적용 후 기영에게 전달
  - max_seq_len = 64로 지정 후 pr 날리기
- 재훈
  - training hyperparameter set 제작 후 사용법 공유
  - 한 사람 지피유 할당 넘을 시 체크포인트 전달해서 그 부분부터 계속할 수 있도록 진행

**Comment by Jaehun-Kim22** [comment]
@autumnluv augmentation 적용 완료하고 기영이 형한테 넘긴 후에 적용 예시를 여기에 캡쳐나 다른 방식으로 제가 확인할 수 있게 공유 부탁드릴게요.
@michael960725 데이터 제작 완료하고 TREE가 어떻게 이루어졌는지 여기에 공유 부탁할게

**Comment by autumnluv** [comment]
<img width="219" alt="augment예시" src="https://user-images.githubusercontent.com/87290147/129820695-0293ab9c-bb2d-4e58-b6e5-d687dccaae54.png">

**Comment by autumnluv** [comment]
<img width="609" alt="augment예시2" src="https://user-images.githubusercontent.com/87290147/129820765-70aed957-8eda-4064-afd6-1242959224f0.png">
